/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package votasys;

/**
 *
 * @author zlaifer
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_admin = new javax.swing.JDialog();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric6 = new org.edisoncor.gui.label.LabelMetric();
        btn_nuevo = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_salirm = new javax.swing.JButton();
        labelMetric8 = new org.edisoncor.gui.label.LabelMetric();
        lblnom_usu = new org.edisoncor.gui.label.LabelMetric();
        jLabel8 = new javax.swing.JLabel();
        labelMetric10 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        btn_tipo_mtvo = new javax.swing.JButton();
        labelMetric11 = new org.edisoncor.gui.label.LabelMetric();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menu_invitado = new javax.swing.JDialog();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric12 = new org.edisoncor.gui.label.LabelMetric();
        btn_nuevo1 = new javax.swing.JButton();
        btn_consultar1 = new javax.swing.JButton();
        btn_salirm1 = new javax.swing.JButton();
        labelMetric13 = new org.edisoncor.gui.label.LabelMetric();
        lblnom_usu1 = new org.edisoncor.gui.label.LabelMetric();
        jLabel14 = new javax.swing.JLabel();
        labelMetric14 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric5 = new org.edisoncor.gui.label.LabelMetric();
        btn_tipo_mtvo1 = new javax.swing.JButton();
        labelMetric15 = new org.edisoncor.gui.label.LabelMetric();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_acceder = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        tex_usuario = new org.edisoncor.gui.textField.TextFieldRoundImage();
        tex_pass = new org.edisoncor.gui.passwordField.PasswordFieldRoundImage();
        jLabel2 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_prueba = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();

        menu_admin.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        menu_admin.setMinimumSize(new java.awt.Dimension(948, 459));
        menu_admin.setResizable(false);
        menu_admin.getContentPane().setLayout(null);

        labelMetric2.setBackground(new java.awt.Color(153, 255, 255));
        labelMetric2.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric2.setText("MENU PRINCIPAL");
        labelMetric2.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menu_admin.getContentPane().add(labelMetric2);
        labelMetric2.setBounds(0, 10, 940, 40);

        labelMetric6.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric6.setText("USUARIOS");
        labelMetric6.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_admin.getContentPane().add(labelMetric6);
        labelMetric6.setBounds(90, 120, 180, 40);

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_usuario-mod.png"))); // NOI18N
        btn_nuevo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseMoved(evt);
            }
        });
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        btn_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_nuevoKeyReleased(evt);
            }
        });
        menu_admin.getContentPane().add(btn_nuevo);
        btn_nuevo.setBounds(90, 170, 180, 90);

        btn_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_btnnuevo-mod.png"))); // NOI18N
        btn_consultar.setName(""); // NOI18N
        btn_consultar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_consultarMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_consultarMouseMoved(evt);
            }
        });
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        btn_consultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_consultarKeyReleased(evt);
            }
        });
        menu_admin.getContentPane().add(btn_consultar);
        btn_consultar.setBounds(280, 170, 180, 90);

        btn_salirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_exit-mod.png"))); // NOI18N
        btn_salirm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_salirmMouseMoved(evt);
            }
        });
        btn_salirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirmActionPerformed(evt);
            }
        });
        btn_salirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_salirmKeyReleased(evt);
            }
        });
        menu_admin.getContentPane().add(btn_salirm);
        btn_salirm.setBounds(660, 170, 180, 90);

        labelMetric8.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric8.setText("SALIR");
        labelMetric8.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_admin.getContentPane().add(labelMetric8);
        labelMetric8.setBounds(660, 120, 180, 40);

        lblnom_usu.setForeground(new java.awt.Color(0, 0, 0));
        lblnom_usu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnom_usu.setColorDeSombra(new java.awt.Color(204, 204, 204));
        menu_admin.getContentPane().add(lblnom_usu);
        lblnom_usu.setBounds(260, 320, 440, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        menu_admin.getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 320, 560, 40);

        labelMetric10.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMetric10.setText("USUARIO:");
        labelMetric10.setColorDeSombra(new java.awt.Color(204, 204, 204));
        menu_admin.getContentPane().add(labelMetric10);
        labelMetric10.setBounds(180, 320, 80, 40);

        labelMetric3.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric3.setText("CANDIDATOS");
        labelMetric3.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_admin.getContentPane().add(labelMetric3);
        labelMetric3.setBounds(280, 120, 180, 40);

        btn_tipo_mtvo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_votar-mod.png"))); // NOI18N
        btn_tipo_mtvo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_tipo_mtvoMouseMoved(evt);
            }
        });
        btn_tipo_mtvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tipo_mtvoActionPerformed(evt);
            }
        });
        btn_tipo_mtvo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_tipo_mtvoKeyReleased(evt);
            }
        });
        menu_admin.getContentPane().add(btn_tipo_mtvo);
        btn_tipo_mtvo.setBounds(470, 170, 180, 90);

        labelMetric11.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric11.setText("VOTACION");
        labelMetric11.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_admin.getContentPane().add(labelMetric11);
        labelMetric11.setBounds(470, 120, 180, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        menu_admin.getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 60, 860, 320);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        menu_admin.getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 100, 810, 190);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_fondo1.jpg"))); // NOI18N
        menu_admin.getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 950, 460);

        menu_invitado.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        menu_invitado.setMinimumSize(new java.awt.Dimension(948, 461));
        menu_invitado.setResizable(false);
        menu_invitado.getContentPane().setLayout(null);

        labelMetric4.setBackground(new java.awt.Color(153, 255, 255));
        labelMetric4.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric4.setText("MENU PRINCIPAL");
        labelMetric4.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menu_invitado.getContentPane().add(labelMetric4);
        labelMetric4.setBounds(0, 10, 940, 40);

        labelMetric12.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric12.setText("CONSULTAR C.");
        labelMetric12.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_invitado.getContentPane().add(labelMetric12);
        labelMetric12.setBounds(90, 120, 180, 40);

        btn_nuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_consultar1-mod.png"))); // NOI18N
        btn_nuevo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_nuevo1MouseMoved(evt);
            }
        });
        btn_nuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo1ActionPerformed(evt);
            }
        });
        btn_nuevo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_nuevo1KeyReleased(evt);
            }
        });
        menu_invitado.getContentPane().add(btn_nuevo1);
        btn_nuevo1.setBounds(90, 170, 180, 90);

        btn_consultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_propusta-mod.png"))); // NOI18N
        btn_consultar1.setName(""); // NOI18N
        btn_consultar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_consultar1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_consultar1MouseMoved(evt);
            }
        });
        btn_consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar1ActionPerformed(evt);
            }
        });
        btn_consultar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_consultar1KeyReleased(evt);
            }
        });
        menu_invitado.getContentPane().add(btn_consultar1);
        btn_consultar1.setBounds(280, 170, 180, 90);

        btn_salirm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_exit-mod.png"))); // NOI18N
        btn_salirm1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_salirm1MouseMoved(evt);
            }
        });
        btn_salirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirm1ActionPerformed(evt);
            }
        });
        btn_salirm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_salirm1KeyReleased(evt);
            }
        });
        menu_invitado.getContentPane().add(btn_salirm1);
        btn_salirm1.setBounds(660, 170, 180, 90);

        labelMetric13.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric13.setText("SALIR");
        labelMetric13.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_invitado.getContentPane().add(labelMetric13);
        labelMetric13.setBounds(660, 120, 180, 40);

        lblnom_usu1.setForeground(new java.awt.Color(0, 0, 0));
        lblnom_usu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnom_usu1.setColorDeSombra(new java.awt.Color(204, 204, 204));
        menu_invitado.getContentPane().add(lblnom_usu1);
        lblnom_usu1.setBounds(260, 320, 440, 40);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        menu_invitado.getContentPane().add(jLabel14);
        jLabel14.setBounds(160, 320, 560, 40);

        labelMetric14.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMetric14.setText("USUARIO:");
        labelMetric14.setColorDeSombra(new java.awt.Color(204, 204, 204));
        menu_invitado.getContentPane().add(labelMetric14);
        labelMetric14.setBounds(180, 320, 80, 40);

        labelMetric5.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric5.setText("PROPUESTAS C.");
        labelMetric5.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_invitado.getContentPane().add(labelMetric5);
        labelMetric5.setBounds(280, 120, 180, 40);

        btn_tipo_mtvo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_votar-mod.png"))); // NOI18N
        btn_tipo_mtvo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_tipo_mtvo1MouseMoved(evt);
            }
        });
        btn_tipo_mtvo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tipo_mtvo1ActionPerformed(evt);
            }
        });
        btn_tipo_mtvo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_tipo_mtvo1KeyReleased(evt);
            }
        });
        menu_invitado.getContentPane().add(btn_tipo_mtvo1);
        btn_tipo_mtvo1.setBounds(470, 170, 180, 90);

        labelMetric15.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric15.setText("VOTACION");
        labelMetric15.setColorDeSombra(new java.awt.Color(204, 204, 204));
        labelMetric15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu_invitado.getContentPane().add(labelMetric15);
        labelMetric15.setBounds(470, 120, 180, 40);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        menu_invitado.getContentPane().add(jLabel21);
        jLabel21.setBounds(40, 60, 860, 320);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setForeground(new java.awt.Color(204, 0, 51));
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        menu_invitado.getContentPane().add(jLabel22);
        jLabel22.setBounds(60, 100, 810, 190);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_fondo1.jpg"))); // NOI18N
        menu_invitado.getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 950, 460);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1176, 599));
        setName("sistema"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1176, 599));
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame1.setTitle("SISTEMA DE VOTACION");
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_usuario-mod.png"))); // NOI18N
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTRASEÑA");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 100, 130, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USUARIO");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 40, 130, 20);

        btn_acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_aceptar-mod.png"))); // NOI18N
        btn_acceder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_accederMouseMoved(evt);
            }
        });
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btn_acceder);
        btn_acceder.setBounds(220, 170, 90, 40);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_cancelar-mod.png"))); // NOI18N
        btn_salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_salirMouseMoved(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btn_salir);
        btn_salir.setBounds(320, 170, 90, 40);

        tex_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tex_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tex_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tex_usuarioKeyReleased(evt);
            }
        });
        jInternalFrame1.getContentPane().add(tex_usuario);
        tex_usuario.setBounds(220, 60, 190, 30);

        tex_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tex_pass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tex_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tex_passKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tex_passKeyReleased(evt);
            }
        });
        jInternalFrame1.getContentPane().add(tex_pass);
        tex_pass.setBounds(220, 120, 190, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_login-mod.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 160, 160);
        jInternalFrame1.getContentPane().add(lbl_fecha);
        lbl_fecha.setBounds(120, 10, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("FECHA ACTUAL:");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 10, 90, 30);
        jInternalFrame1.getContentPane().add(lbl_prueba);
        lbl_prueba.setBounds(324, 0, 100, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V_fondo1.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 480, 240);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(320, 150, 485, 263);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio);
        escritorio.setBounds(0, 0, 1180, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accederMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accederMouseMoved
        btn_acceder.setToolTipText("ACCEDER");
    }//GEN-LAST:event_btn_accederMouseMoved

    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed

    }//GEN-LAST:event_btn_accederActionPerformed

    private void btn_salirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseMoved
        btn_salir.setToolTipText("SALIR");
    }//GEN-LAST:event_btn_salirMouseMoved

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void tex_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tex_usuarioKeyReleased

    }//GEN-LAST:event_tex_usuarioKeyReleased

    private void tex_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tex_passKeyPressed

    }//GEN-LAST:event_tex_passKeyPressed

    private void tex_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tex_passKeyReleased

    }//GEN-LAST:event_tex_passKeyReleased

    private void btn_nuevoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseMoved
        btn_nuevo.setToolTipText("USUARIOS");
    }//GEN-LAST:event_btn_nuevoMouseMoved

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_nuevoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_nuevoKeyReleased

    }//GEN-LAST:event_btn_nuevoKeyReleased

    private void btn_consultarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseDragged
        //JOptionPane.showMessageDialog(null, "pasaste el mouse aqui");
    }//GEN-LAST:event_btn_consultarMouseDragged

    private void btn_consultarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseMoved
        btn_consultar.setToolTipText("CANDIDATOS");
    }//GEN-LAST:event_btn_consultarMouseMoved

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed

    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_consultarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_consultarKeyReleased

    }//GEN-LAST:event_btn_consultarKeyReleased

    private void btn_salirmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirmMouseMoved
        btn_salirm.setToolTipText("SALIR");
    }//GEN-LAST:event_btn_salirmMouseMoved

    private void btn_salirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirmActionPerformed

    }//GEN-LAST:event_btn_salirmActionPerformed

    private void btn_salirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_salirmKeyReleased

    }//GEN-LAST:event_btn_salirmKeyReleased

    private void btn_tipo_mtvoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tipo_mtvoMouseMoved
        btn_tipo_mtvo.setToolTipText("VOTACIONES");
    }//GEN-LAST:event_btn_tipo_mtvoMouseMoved

    private void btn_tipo_mtvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tipo_mtvoActionPerformed

    }//GEN-LAST:event_btn_tipo_mtvoActionPerformed

    private void btn_tipo_mtvoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_tipo_mtvoKeyReleased

    }//GEN-LAST:event_btn_tipo_mtvoKeyReleased

    private void btn_nuevo1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevo1MouseMoved
        btn_nuevo1.setToolTipText("CONSULTAR CANDIDATO");
    }//GEN-LAST:event_btn_nuevo1MouseMoved

    private void btn_nuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevo1ActionPerformed

    private void btn_nuevo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_nuevo1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevo1KeyReleased

    private void btn_consultar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultar1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar1MouseDragged

    private void btn_consultar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultar1MouseMoved
        btn_consultar1.setToolTipText("PROPUSTAS");
    }//GEN-LAST:event_btn_consultar1MouseMoved

    private void btn_consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar1ActionPerformed

    private void btn_consultar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_consultar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar1KeyReleased

    private void btn_salirm1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirm1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirm1MouseMoved

    private void btn_salirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirm1ActionPerformed

    private void btn_salirm1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_salirm1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirm1KeyReleased

    private void btn_tipo_mtvo1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tipo_mtvo1MouseMoved
        btn_tipo_mtvo1.setToolTipText("VOTAR");
    }//GEN-LAST:event_btn_tipo_mtvo1MouseMoved

    private void btn_tipo_mtvo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tipo_mtvo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tipo_mtvo1ActionPerformed

    private void btn_tipo_mtvo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_tipo_mtvo1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tipo_mtvo1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acceder;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_consultar1;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_nuevo1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_salirm;
    private javax.swing.JButton btn_salirm1;
    private javax.swing.JButton btn_tipo_mtvo;
    private javax.swing.JButton btn_tipo_mtvo1;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.label.LabelMetric labelMetric10;
    private org.edisoncor.gui.label.LabelMetric labelMetric11;
    private org.edisoncor.gui.label.LabelMetric labelMetric12;
    private org.edisoncor.gui.label.LabelMetric labelMetric13;
    private org.edisoncor.gui.label.LabelMetric labelMetric14;
    private org.edisoncor.gui.label.LabelMetric labelMetric15;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric5;
    private org.edisoncor.gui.label.LabelMetric labelMetric6;
    private org.edisoncor.gui.label.LabelMetric labelMetric8;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_prueba;
    public static org.edisoncor.gui.label.LabelMetric lblnom_usu;
    public static org.edisoncor.gui.label.LabelMetric lblnom_usu1;
    private javax.swing.JDialog menu_admin;
    private javax.swing.JDialog menu_invitado;
    public static org.edisoncor.gui.passwordField.PasswordFieldRoundImage tex_pass;
    public static org.edisoncor.gui.textField.TextFieldRoundImage tex_usuario;
    // End of variables declaration//GEN-END:variables
}
